spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate

jwt:
  secret-key: ${JWT_SECRET_KEY}

github:
  username: ${GITHUB_USERNAME}
  pat: ${GITHUB_PAT}
