spring:
  application:
    name: proxia
    version: 1.0.0
  jpa:
    open-in-view: false

jwt:
  secret-key: ${JWT_SECRET_KEY}
  access-token-expiration: 3600000
  refresh-token-expiration: 86400000

oauth2:
  github:
    client-id: ${GITHUB_CLIENT_ID}
    client-secret: ${GITHUB_CLIENT_SECRET}

git:
  integration:
    github:
      client-id: ${GIT_INTEGRATION_GITHUB_CLIENT_ID}
      client-secret: ${GIT_INTEGRATION_GITHUB_CLIENT_SECRET}

---
spring.config.activate.on-profile: local

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:proxia;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true

---
spring.config.activate.on-profile: dev