spring:
  application:
    name: proxia
    version: 0.1.0
  jpa:
    open-in-view: false

jwt:
  access-token-expiration: 3600000
  refresh-token-expiration: 86400000

encryption:
  secret-key: ${ENCRYPTION_SECRET_KEY}

oauth2:
  github:
    client-id: ${GITHUB_CLIENT_ID}
    client-secret: ${GITHUB_CLIENT_SECRET}

git:
  integration:
    github:
      client-id: ${GIT_INTEGRATION_GITHUB_CLIENT_ID}
      client-secret: ${GIT_INTEGRATION_GITHUB_CLIENT_SECRET}

webhook:
  github:
    secret: ${WEBHOOK_GITHUB_SECRET:}

github:
  username: ${GITHUB_USERNAME}
  pat: ${GITHUB_PAT}
